# Copyright (c) 2020, eQualit.ie inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.


version: '3'
services:
    es_retriever:
        build:
          context: .
          dockerfile: Dockerfile
          args:
            - BRANCH=${BRANCH}
        env_file:
          - .env
        command: python simple_retrieve_cli.py ${ELK_HOST} es-index es-index-type "2019-09-01 00:00:00" "2019-09-01 00:03:00" -u ${ELK_USER} -p -o /data/testdata
        stdin_open: true
        tty: true
        volumes:
          - ./data:/data
        ports:  # for spark UI
          - "4040:4040"
          - "4041:4041"

volumes:
  data-volume:
